# Identical to main testing workflow, but points only
# at dev branch
name: build[master]
on:
  push:
    branches: [master]
jobs:
  # Build the Traces application
  build-traces:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nhartland/love-build@master
        id: Traces-Master
        with:
          app_name: "Traces"
          love_version: "11.4"
          source_dir: "."

      # Upload the resulting artifacts
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: MacOS
          path: ${{ steps.Traces-Master.outputs.macos-filename }}
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: Win32
          path: ${{ steps.Traces-Master.outputs.win32-filename }}
      - uses: actions/upload-artifact@v3.0.0
        with:
          name: Win64
          path: ${{ steps.Traces-Master.outputs.win64-filename }}
